stages:
  - test

variables:
  BASE_URL: https://api.restful-api.dev
  TIMEOUT: 30000

before_script:
  - npm install
  - npx playwright install

test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - playwright-report/
    when: always
